version: '2'

services:
  web:
    restart: always
    image: nginx:1.11
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/servers.conf:/etc/nginx/conf.d/servers.conf
